### ISSUE TITLE
Name on the search dropdown is not updated properly while changing page from browser's URL bar

### ISSUE THREAD

**Issue by dhamodaran-pandiyan** [devgg/gh-issues#13]
Steps to reproduce:
1. Open this link : https://gauger.io/
2. Click this hyperlink on that page: "gauger.io/contrib" 
3. By default, it'll redirect to **javascript page**. Like [this](https://gauger.io/contrib/#/language/javascript).
4. Till this point, everything is perfect. 
5. Now, On your browser's search bar, replace **javascript** with **python** in the URL: https://gauger.io/contrib/#/language/javascript, like this: https://gauger.io/contrib/#/language/python and hit enter.
6. As you can see, page reloaded with python projects and python description, but the search bar still has the text javascript.

Is this expected?

If it is expected, consider this issue as an enhancement, because seeing a page with python description and python projects with the Javascript as a searchbar placeholder doesn't look great.

![InkedScreenshot_2020-08-24 Contrib 👩‍💻👨‍💻 Find Open Source Projects To Contribute To 🔥_LI](https://user-images.githubusercontent.com/18031856/91015008-11253780-e608-11ea-960e-08115312696f.jpg)

**Comment by devgg** [comment]
Thank you for the detailed issue!
